### ISSUE TITLE
TypeError on fresh install

### ISSUE THREAD

**Issue by johngeorgewright** [mikaelbr/mversion#32]
This could potentially be caused by a third party API, or perhaps an incorrect use of a third party API.

```
$ node -v
v0.12.2

$ mversion -h
node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:1226
    throw e;
          ^
TypeError: undefined is not a function
Please report this to https://github.com/chjj/marked.
    at InlineLexer.output (node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:685:28)
    at Parser.tok (node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:985:21)
    at Parser.parse (node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:935:17)
    at Function.Parser.parse (/node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:922:17)
    at marked (node_modules/mversion/node_modules/cli-usage/node_modules/marked/lib/marked.js:1218:19)
    at fromFile (node_modules/mversion/node_modules/cli-usage/index.js:45:10)
    at get (node_modules/mversion/node_modules/cli-usage/index.js:30:12)
    at module.exports (node_modules/mversion/node_modules/cli-usage/index.js:22:15)
    at Object.<anonymous> (node_modules/mversion/bin/cli.js:9:1)
    at Module._compile (module.js:460:26)
```

**Comment by mikaelbr** [comment]
Thanks for letting me know! Patched and fixed now. Was an error with `marked-terminal` not supporting a new feature from the `marked` library - used for readme and usage help.
